[[feature]]
date = "2024-05-09"
animal = "Argentine ant"
latin = "Linepithema humile"
image = "https://upload.wikimedia.org/wikipedia/commons/3/3f/Linepithema_Argentine_ant.jpg"
feature = [
	"Argentine ants are native to South America, but have spread across much of the world and are rated among the world's most invasive species. They are the most common species of ant in California, nesting opportunistically underground, in leaf litter, in cracks in concrete, between boards, and even in our homes.",
	
	"Thanks to research performed in California, it was discovered that Argentine ants form super-colonies in which the workers and queens of separate nests mix freely among each other and dominate the areas they invade. Despite this, super colonies do clash. In 2004, it was estimated that the Very Large Colony and Lake Hodges Colony saw millions of casualties every month along a frontline that was a few miles long and only a few centimeters wide.",
	
	'The ants have disrupted natural and agricultural environments across the world. The tend aphids, mealybugs, and scale insects, which they harvest for a substance called "honeydew." Their protection of these plant pests, leads to an increase in their population and therefore local crop damage.'
]

[[feature]]
date = "2024-05-13"
animal = "Peninsular Bighorn Sheep"
latin = "Ovis canadensis cremnobates"
image = "https://www.ndow.org/wp-content/uploads/2021/10/ovis_canadensis_nelsoni.jpeg"
feature = [
	"The peninsular bighorn sheep is native to the mountain ranges stretching from Southern California to the US-Mexico border, living in large herds without a dominance hierarchy. Rams establish dominance only during the mating season to determine access to partners. Their dominance display is like a gun duel: walking away from each other, turning to face each other, then lunging into headbutts.",

	"Bighorn sheep are susceptible to scabies and pneumonia. Unlike other bighorn sheep, the Peninsular bighorn can go without water for extended periods. Their primary predators are black bears, grizzly bears, wolves, and mountain lions. Due to human fire suppression techniques in their natural habitat, there is increased cover available for predators, leading to increased predation. Since they are so sensitive to human-induced environmental issues, they are considered a good indicator of a healthy local environment.",

	"Aside from their exhibit at the Safari Park, they can be seen in Anza-Borrego Desert State Park, Joshua Tree Nation Park, Death Valley National Park, and the Mojave National Preserve. They are featured on a US Postal Service Forever stamp as part of the Endangered Species set and are the the state mammal of Nevada and the mascot of the Autonomous University of Baja California."
]

[[feature]]
date = "2024-05-20"
animal = "California Sea Lion"
latin = "Zalophus californianus"
image = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Lion_de_mer_Amn%C3%A9ville_01.jpg/800px-Lion_de_mer_Amn%C3%A9ville_01.jpg"
feature = [
	'The California Sea Lion is native to the North American west coast, stretching from central Mexico to southeast Alaska, and are one of six species of sea lions or "eared seals." Males establish breeding territory on land and on and underwater where they will stay during the entire breeding time, relying on their blubber to keep them fed. They can stay at sea for two weeks at a time and make continuous dives, returning to the surface to rest.',

	"The sea lion population off the west coast of the US is near its natural capacity. They endanger local fish populations in Oregon, Washington, and Idaho. These three states and six regional tribes are permitted to cull their population by as many as 540 California sea lions and 176 Steller sea lions between 2020 and 2025. California has attempted to ward off sea lions from endangered salmon species with bombs, rubber bullets and bean bags to no effect.",

	"Along with dolphins and other seal species, they are part of the Navy Marine Mammal Program based in San Diego Bay. In this program, the Navy trains them to locate intruders to harbor installations and around ships, and to recover test equipment dropped by ships or planes. The Navy claims that it has never trained marine animals for attack missions because they are not able to tell the difference between enemy and friendly vessels."
]

[[feature]]
date = "2024-12-01"
animal = "Anna's Hummingbird"
latin = "Calypte anna"
image = "https://upload.wikimedia.org/wikipedia/commons/c/c4/Anna%27s_hummingbird.jpg"
feature = [
"Anna's hummingbird (Calypte anna) is a North American species of hummingbird. Native to the North American West coast, they bred only in Baja and Southern California during the 20th century. The transplanting of exotic ornamental plants in residential areas throughout the Pacific coast and inland deserts provided expanded nectar and nesting sites, allowing the species to expand its breeding range.",

"The male is the only North American hummingbird species with a red crown. The color and iridescence of this crown depends on the bird's protein intake. Females and juvenile males have a dull green crown, a grey throat with or without some red iridescence, a grey chest and belly, and a dark, rounded tail with white tips on the outer feathers.",

"Birds with inadequate stores of body fat or insufficient plumage are able to survive periods of subfreezing weather by lowering their metabolic rate and entering a state of torpor.",

"They assist in pollinating plants via an electrostatic charge they build during flight. This causes them to pick up pollen as they feed on a flower's nectar and deposit it on another flower.",

"It is one of the few hummingbirds [that uses song](https://en.m.wikipedia.org/wiki/File:Calypte_anna_-_Anna%27s_Hummingbird_-_XC109651.ogg) during courtship. They also fly high into the sky and then dive near females to attract their attention. They occasionally hybridize with other hummingbird species and those offspring are often mistaken for new species.",

"It was named after Anna Masséna, Duchess of Rivoli. Masséna was married to an ornithologist and was senior lady-in-waiting) to [Eugénie de Montijo](https://en.m.wikipedia.org/wiki/Empress_Eug%C3%A9nie_Surrounded_by_her_Ladies_in_Waiting) Empress of France and wife of Napoleon III. A colleague of Masséna's amateur ornithologist husband, naturalist René Lesson, named the bird after her. Lesson published several books on humming birds, and one on birds in general. He also named and described many new amphibian species and was the first person to see birds of paradise in the wild.",

"Anna's hummingbirds are the official bird of the city of Vancouver, BC, and are non-migrating residents of Seattle, WA."
]
